# Generated by Django 6.0.5 on 2026-05-21 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['side', 'order', 'name']},
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(default='Belum ada Deskripsi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='side',
            field=models.CharField(choices=[('left', 'Left Panel'), ('right', 'Right Panel')], default='left', max_length=10),
        ),
        migrations.AddField(
            model_name='skill',
            name='subtitle',
            field=models.CharField(default='Belum ada data', max_length=150),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SkillPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='portofolio.skill')),
            ],
            options={
                'ordering': ['order', 'text'],
            },
        ),
        migrations.CreateModel(
            name='SkillTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='portofolio.skill')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
