# Generated by Django 6.0.5 on 2026-05-21 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0002_alter_skill_options_skill_description_skill_side_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilltag',
            name='skill',
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order', 'name']},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='side',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='subtitle',
        ),
        migrations.DeleteModel(
            name='SkillPoint',
        ),
        migrations.DeleteModel(
            name='SkillTag',
        ),
    ]
